export const DI_LIST = {
  // treeNode: Symbol.for('TreeNode'),
  treeNodeConstructor: Symbol.for('TreeNodeConstructor'),
  collapsableNode: Symbol.for('CollapsableNode'),
  // draggableNode: Symbol.for('DraggableNode'),
  draggableNodeConstructor: Symbol.for('DraggableNodeConstructor'),
  draggableNodeFactory: Symbol.for('DraggableNodeFactory'),
  dragNodeAction: Symbol.for('DragNodeAction'),
  treeStore: Symbol.for('TreeStore'),
  treant: Symbol.for('Treant'),
  nodeDB: Symbol.for('NodeDB'),
  tree: Symbol.for('Tree'),
  util: Symbol.for('Util'),
  imageLoader: Symbol.for('ImageLoader'),
  nodeDBState: Symbol.for('NodeDBState'),
  jsonConfig: Symbol.for('JSONconfig'),
  pointlineChart: Symbol.for('pointlineChart'),
  selection: Symbol.for('selection'),
  pointlineActions: Symbol.for('pointlineActions'),
  pointlineJS: Symbol.for('pointlineJS'),
  tooltip: Symbol.for('Tooltip'),
  pointlineZoom: Symbol.for('pointlineZoom'),
  collapsableNodesStore: Symbol.for('CollapsableNodesStore'),
};
