export const DI_LIST = {
  treeNode: Symbol.for('TreeNode'),
  collapsableNode: Symbol.for('CollapsableNode'),
  treeStore: Symbol.for('TreeStore'),
  treant: Symbol.for('Treant'),
  nodeDB: Symbol.for('NodeDB'),
  tree: Symbol.for('Tree'),
  util: Symbol.for('Util'),
  imageLoader: Symbol.for('ImageLoader'),
  nodeDBState: Symbol.for('NodeDBState'),
  jsonConfig: Symbol.for('JSONconfig'),
  pointlineChart: Symbol.for('pointlineChart'),
  selection: Symbol.for('selection'),
  pointlineActions: Symbol.for('pointlineActions'),
  pointlineJS: Symbol.for('pointlineJS'),
  tooltip: Symbol.for('Tooltip'),
};
