# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages

name: Github Package

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Github-packages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: jaywcjlove/github-action-package@main
        with:
          node-version: 20.18.1
          registry-url: https://npm.pkg.github.com
          data: |
            {
              "publishConfig": {
                "registry": "https://npm.pkg.github.com"
              },
              "repository": "https://github.com/egor-progger/pointlinejs.git"
            }
      - run: npm ci
      - run: npm run prepare-publish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
